name: Windows CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Cppcheck
        shell: pwsh
        run: |
          choco install cppcheck -y
          $cppcheckPath = "C:\Program Files\Cppcheck"
          $env:PATH += ";$cppcheckPath"
          Write-Host "Updated PATH: $env:PATH"

      - name: Run Cppcheck
        shell: cmd
        run: |
            "%ProgramFiles%\Cppcheck\cppcheck.exe" ^
              --enable=all ^
              --inconclusive ^
              --std=c++20 ^
              --suppress=missingInclude ^
              --suppress=missingIncludeSystem ^
              --output-file=cppcheck-report.txt ^
              development

      - name: Display Report
        shell: pwsh
        run: |
          Write-Host "==== Cppcheck output ===="
          Get-Content cppcheck-report.txt

      - name: Upload Cppcheck Report
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck-report.txt

  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build project
        run: cmake --build build --config Release

      - name: Run run-time tests (GoogleTest)
        shell: pwsh
        run: .\build\test\run_time\Release\hsm_run_time_tests.exe

      - name: Run compile-time tests (CTest)
        run: ctest --test-dir build -C Release --output-on-failure -L compile_time
